### ISSUE TITLE
Please support 1.8+ 

### ISSUE THREAD

**Issue by TymekSL** [jcurtis06/RockPaperScissors#8]
Could you add support for older version 1.8+ and add more images ;> (and fix current images when there is 404)

**Comment by jcurtis06** [comment]
Thanks for bringing the images to my attention. Unfortunately supporting 1.8 will severely complicate the plugin as the methods for creating GUIs have changed a lot since then. A better solution would be to use **Geyser**. I apologize for any inconvenience!

**Comment by TymekSL** [comment]
lol i wont use geyser ? so can u add support 1.9+ ? where you have problem?

**Comment by jcurtis06** [comment]
It is not high on my list of priorities. I may add it eventually. I would have to implement reflection, which is pretty complex for such a simple plugin. I know it is unfortunate, but please understand that supporting 1.8 all the way to 1.20 is going to be difficult.
